import { createReadStream, type ReadStream } from "node:fs";
import { mkdir, rename, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * Storage for uploaded media. Keys are generated by the server
 * (`YYYY/MM/<uuid>.<ext>`), never taken from user input. The interface allows an
 * object-store driver (S3-compatible) to be added without touching callers.
 */
export interface StorageDriver {
  readonly name: string;
  put(key: string, body: Buffer): Promise<void>;
  read(key: string, range?: { start: number; end: number }): Promise<ReadStream>;
  size(key: string): Promise<number | null>;
  remove(key: string): Promise<void>;
  usage(): Promise<{ files: number; totalBytes: number } | null>;
}

const KEY_PATTERN = /^\d{4}\/\d{2}\/[a-f0-9-]{36}\.[a-z0-9]{2,5}$/;

export function isValidStorageKey(key: string): boolean {
  return KEY_PATTERN.test(key);
}

export class LocalStorage implements StorageDriver {
  readonly name = "local";

  constructor(private readonly root: string) {}

  private resolve(key: string): string {
    if (!isValidStorageKey(key)) throw new Error(`Invalid storage key: ${key}`);
    const full = path.resolve(this.root, key);
    if (!full.startsWith(path.resolve(this.root) + path.sep))
      throw new Error("Storage path escapes root");
    return full;
  }

  async put(key: string, body: Buffer): Promise<void> {
    const target = this.resolve(key);
    await mkdir(path.dirname(target), { recursive: true });
    // Write to a temporary file first so readers never see a partial upload.
    const temp = `${target}.${process.pid}.tmp`;
    await writeFile(temp, body, { mode: 0o640 });
    await rename(temp, target);
  }

  async read(key: string, range?: { start: number; end: number }): Promise<ReadStream> {
    return createReadStream(this.resolve(key), range);
  }

  async size(key: string): Promise<number | null> {
    try {
      const info = await stat(this.resolve(key));
      return info.isFile() ? info.size : null;
    } catch {
      return null;
    }
  }

  async remove(key: string): Promise<void> {
    await rm(this.resolve(key), { force: true });
  }

  async usage(): Promise<null> {
    // Totals come from the media table, which is authoritative.
    return null;
  }
}
